if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(ARCH_DEFINES -D_LINUX -DTARGET_POSIX -DTARGET_LINUX)
  if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(ARCH x86_64-linux)
  endif()
  set(SYSTEM_DEFINES -D__STDC_CONSTANT_MACROS 
                     -D_FILE_DEFINED -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64)
  set(DEP_DEFINES -DLIRC_DEVICE=${LIRC_DEVICE})
endif()
